name: "New Release"

on:
  milestone:
    types: [closed]
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GO: 1.17

jobs:
  bump-version:
    if: github.event_name == 'milestone'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO }}

      - name: Configure Git
        run: |
          git config user.name "sv-tools-bot"
          git config user.email "sv.go.tools@gmail.com"
          git fetch --all

      - name: Create Tag
        run: |
          docker run --rm -v $PWD:/mount -w /mount svtools/bumptag:latest ${{ github.event.milestone.title }}

      - name: Push Tag
        run: git push origin --tags

      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@v1.1
        with:
          title: Next
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  release-cli:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO }}

      - name: Prepare gpg
        run: |
          gpgconf --kill gpg-agent
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output .github/sv-tools-bot.asc .github/sv-tools-bot.asc.gpg
          gpg --batch --yes --import .github/sv-tools-bot.asc
          rm .github/sv-tools-bot.asc

      - name: Allow arm Docker builds # https://github.com/linuxkit/linuxkit/tree/master/pkg/binfmt
        run: sudo docker run --privileged linuxkit/binfmt:v0.8

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: sv-tools-bot
          password: ${{ secrets.BOT_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: svtools
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Snapcraft Login
        env:
          SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
        run: |
          sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
          snapcraft login --with <(echo "$SNAPCRAFT_LOGIN")

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --config .github/goreleaser-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
